version: "3.9"
services:
  backend:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: backend
    env_file:
      - src/main/resources/secret.env
    ports:
      - "8100:8100"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15.3-alpine
    env_file:
      - src/main/resources/secret.env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local